version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - "./docker/nginx/etc/default.conf:/etc/nginx/conf.d/default.conf:cached"
      - "./src/:/var/www/:cached"
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - mysql
      - mysql_test
      - redis
    environment:
      - PHP_RUN_COMPOSER_INSTALL=true
    volumes:
      - "./src/:/var/www/:cached"
      - "./src/storage/:/var/www/storage/:cached"
      - "./docker/php/usr/local/bin/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:cached"
      - "./docker/php/etc/custom.ini:/usr/local/etc/php/conf.d/custom.ini"
  scheduler:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    command: ["scheduler"]
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    volumes:
      - "./src/:/var/www/:cached"
      - "./src/storage/:/var/www/storage/:cached"
      - "./docker/php/usr/local/bin/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:cached"
      - "./docker/php/etc/custom.ini:/usr/local/etc/php/conf.d/custom.ini"
  worker:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    command: ["worker"]
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    volumes:
      - "./src/:/var/www/:cached"
      - "./src/storage/:/var/www/storage/:cached"
      - "./docker/php/usr/local/bin/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:cached"
      - "./docker/php/etc/custom.ini:/usr/local/etc/php/conf.d/custom.ini"
  mysql:
    image: mariadb:10.4
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
    ports:
      - "3306:3306"
  mysql_test:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
    ports:
      - "3307:3306"
  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
