input:
  - commonmark
  - creole
  - docbook
  - docx
  - dokuwiki
  - epub
  - fb2
  - gfm
  - haddock
  - html
  - ipynb
  - jats
  - json
  - latex
  - markdown
  - markdown_mmd
  - markdown_phpextra
  - markdown_strict
  - mediawiki
  - man
  - muse
  - native
  - odt
  - opml
  - org
  - rst
  - t2t
  - textile
  - tikiwiki
  - twiki
  - vimwiki
output:
  - asciidoc
  - beamer
  - commonmark
  - context
  - docbook
  - docbook5
  - docx
  - dokuwiki
  - epub
  - epub2
  - fb2
  - gfm
  - haddock
  - html
  - html4
  - icml
  - ipynb
  - jats
  - jira
  - json
  - latex
  - man
  - markdown
  - markdown_mmd
  - markdown_phpextra
  - markdown_strict
  - mediawiki
  - ms
  - muse
  - native
  - odt
  - opml
  - opendocument
  - org
  - pdf
  - plain
  - pptx
  - rst
  - rtf
  - texinfo
  - textile
  - slideous
  - slidy
  - dzslides
  - revealjs
  - s5
  - tei
  - xwiki
  - zimwiki
details:
  - title: AsciiDoc
    name: asciidoc
    default_extension: .asciidoc
    extensions:
      - .asciidoc
      - .adoc
      - .asc
  - title: CommonMark Markdown
    name: commonmark
    default_extension: .md
    extensions:
      - .txt
      - .md
      - .markdown
  - title: Creole 1.0
    name: creole
    default_extension: .creole
    extensions:
      - .creole
  - title: DocBook
    name: docbook
    default_extension: .xml
    extensions:
      - .xml
      - .html
      - .pdf
  - title: Word docx
    name: docx
    slug: word-docx
    default_extension: .docx
    extensions:
      - .docx
  - title: DokuWiki markup
    name: dokuwiki
    default_extension: .txt
    extension:
      - .txt
  - title: EPUB
    name: epub
    default_extension: .epub
    extensions:
      - .epub
  - title: FictionBook2 e-book
    name: fb2
    default_extension: .fb2
    extensions:
      - .fb2
  - title: GitHub-Flavored Markdown
    name: gfm
    slug: github-flavored-markdown
    description: We love Markdown, it's just text. It's so simple and so powerful at the same time. Pure beauty. It's this one standard that works everywhere. Okay, it works a little bit different depending on the platform you are using, but we all agree that the GH flavor is the one and only Markdown flavor, don't we? Actually, I'm not sure what's so special about this MD standard, but never mind. Hopefully you know what's it all about.
    default_extension: .md
    extensions:
      - .txt
      - .md
      - .markdown
  - title: Haddock markup
    name: haddock
  - title: HTML
    name: html
    default_extension: .html
    extensions:
      - .html
  - title: Jupyter notebook
    name: ipynb
    slug: jupyter-notebook
    default_extension: .ipynb
    extensions:
      - .ipynb
  - title: JATS XML
    name: jats
    slug: jats-xml
    default_extension: .xml
    extensions:
      - .xml
  - title: JSON version of native AST
    name: json
    default_extension: .json
    extensions:
      - .txt
      - .json
  - title: LaTeX
    name: latex
    default_extension: .tex
    extensions:
      - .tex
  - title: Pandoc’s Markdown
    name: markdown
    default_extension: .md
    extensions:
      - .txt
      - .md
      - .markdown
  - title: MultiMarkdown
    name: markdown_mmd
    slug: multi-markdown
    default_extension: .md
    extensions:
      - .txt
      - .md
      - .markdown
  - title: PHP Markdown Extra
    name: markdown_phpextra
    slug: php-markdown-extra
    default_extension: .md
    extensions:
      - .txt
      - .md
      - .markdown
  - title: original unextended Markdown
    name: markdown_strict
    slug: strict-markdown
    default_extension: .md
    extensions:
      - .txt
      - .md
      - .markdown
  - title: MediaWiki markup
    name: mediawiki
    slug: mediawiki-markup
  - title: roff man
    name: man
    slug: roff-man
    default_extension: .man
    extensions:
      - .man
      - .mdoc
      - .lb
      - .mandoc
  - title: Muse
    name: muse
    default_extension: .muse
    extensions:
      - .muse
  - title: native Haskell
    name: native
    slug: native-haskell
  - title: ODT
    name: odt
  - title: OPML
    name: opml
  - title: Emacs Org mode
    name: org
    slug: emacs-org-mode
  - title: reStructuredText
    name: rst
    slug: restructured-text
  - title: txt2tags
    name: t2t
  - title: Textile
    name: textile
  - title: TikiWiki markup
    name: tikiwiki
    slug: tikiwiki-markup
  - title: TWiki markup
    name: twiki
    slug: twiki-markup
  - title: Vimwiki
    name: vimwiki
  - title: LaTeX beamer slide show
    name: beamer
    slug: latex-beamer-slide-show
  - title: ConTeXt
    name: context
  - title: DocBook 5
    name: docbook5
  - title: EPUB v2
    name: epub2
  - title: XHTML 1.0 Transitional
    name: html4
  - title: InDesign ICML
    name: icml
    slug: indesign-icml
  - title: Jira wiki markup
    name: jira
    slug: jira-wiki-markup
    description: You said Jira? Isn't this the japanese name for Godzilla? Never mind. I think you're looking for the software. The one software to rule them all. I'm praying for the souls working at Atlassian. I mean this code base must be … big. And actually, I hope for a future where nobody uses Jira. But seems like you're using Jira. Or you work with someone who is using Jira as a project management tool. Or as a wiki. I don't know what you're doing, but I'll include you in my prayers. Good luck converting to this Jira wiki text thing.
  - title: roff ms
    name: ms
  - title: OpenDocument
    name: opendocument
  - title: PDF
    name: pdf
    description: Hey, Portable Document Format. What a name. Sounds like other files are not … portable? It's old, but it works everywhere. Convert to PDF and you can be sure it'll work somehow, even if you the person you're emailing this is 150 years old and has never used a PC before. Good luck with your file!
  - title: plain text
    name: plain
    slug: plain-text
  - title: PowerPoint slide show
    name: pptx
    slug: powerpoint-slide-show
  - title: Rich Text Format
    name: rtf
    slug: rich-text-format
  - title: GNU Texinfo
    name: texinfo
    slug: gnu-texinfo
  - title: Slideous HTML and JavaScript slide show
    name: slideous
  - title: Slidy HTML and JavaScript slide show
    name: slidy
  - title: DZSlides HTML5 + JavaScript slide show
    name: dzslides
  - title: reveal.js HTML5 + JavaScript slide show
    name: revealjs
  - title: S5 HTML and JavaScript slide show
    name: s5
  - title: TEI Simple
    name: tei
    slug: tei-simple
  - title: XWiki markup
    name: xwiki
    slug: xwiki-markup
  - title: ZimWiki markup
    name: zimwiki
    slug: zimwiki-markup
