name: Mirroring

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Copy ENV Laravel Configuration for CI
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies (PHP vendors)
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Execute tests
      run: php artisan test
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          git@git.ueberlab.com:ueberdosis/alldocs.app.git
        ssh_private_key:
          ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
